### ISSUE TITLE
Difference added mass force (moving domain/moving body)

### ISSUE THREAD

**Issue by ddeboerfluid** [WaterLily-jl/WaterLily.jl#160]
Dear all,

I have noticed a significant difference between the added mass force from WaterLily when using a moving domain, compared to a moving body (see figure). Interestingly, after the acceleration stops the forces are very similar again. I noticed it for a plate in 3D first, but it seems to happen in 2D and with other bodies as well. From theoretical added mass values I found for a plate, it seems like the moving body case is approximately correct, and the moving domain case overestimates the force.

What I did: 
1. 2D circle, constant acceleration, then constant velocity. All by mapping the body.
2. 2D circle with same parameters. All by using a moving domain. 

Below I added the code generating the data for the figure (csv file with t* and c_d).

Thank you for helping and I hope you can find out what is causing this.

![c_d](https://github.com/user-attachments/assets/2b581931-d710-47c0-9196-41e213c4dd55)

Moving body code: 

```julia
# Importing
    using WriteVTK, BiotSavartBCs, WaterLily, StaticArrays, CSV, DataFrames
    include("CSV_writer.jl")


    #Simulation settings 

        #Limit time step by overwritting default function
        WaterLily.CFL(a::Flow) = WaterLily.CFL(a; Δt_max=0.2)

    # CSV writer settings 

        #Set attributes 
        t_attrib(a::Simulation, forces) = sum(a.flow.Δt[1:end-1])*a.U/a.L;
        d_attrib(a::Simulation, forces) = forces[1];

        #Make attributes dict 
        attributes_dict         =   Dict("Time [-]" => t_attrib,
                                        "Drag [-]" => d_attrib) 

    #Circle SDF 
        function TwoD_circle_sdf(x, radius, center)
            return √sum(abs2, x .- center) - radius
        end
    
    #Motion function 
        function U_motion(x,t, U, L, acceleration_ND)

            #Get t_i 
            t_i                 =   t*U/L 

            #Get t_acc
            t_acc               =   U/acceleration_ND

            #If accelerating, define motion for accelerating part 
            if t_i<t_acc
                
                x - L*SA[0.5*acceleration_ND*t_i^2,0]
                
            else
                x - L*SA[0.5*acceleration_ND*t_acc^2 + U*(t_i-t_acc),0]
                
            end
        end

    #Function to simulate circle with constant velocity (2D)
    function Circle_acc_to_const(L,Re,domain,acceleration_ND;U=1,ϵ=0.5, f=Array)
        
        #Set radius and center 
        diameter, center  =   L, SA[domain[1]*L/2, domain[2]*L/2]

        #Set sdf 
        sdf     =   (x,t) -> TwoD_circle_sdf(x,diameter/2, center)

        map     =   (x,t) -> U_motion(x,t, U, L, acceleration_ND)

        #Write domain tuple
        domain_tuple    =   tuple(domain*L...)

        #Define simulation and return it
        Simulation(domain_tuple,(0,0),L;U,ν=U*L/Re,body=AutoBody(sdf, map),ϵ, mem=f)
    end

    #Run 
    function run(sim, case_name, t_max_star, wr_CSV, ω)

        #Set t0 to be zero
        t₀ = 0.0 

        #Do actual simulation and store fields and forces
        @time for tᵢ in range(t₀,t₀+t_max_star;step=0.05)

            #Get current time (sum of delta t until now)
            t = sum(sim.flow.Δt[1:end-1])

            #While time is lower than normalised ti, keep running
            while t < tᵢ*sim.L/sim.U

                #Measure 
                measure!(sim,t)
            
                #Calculate forces 
                forces = 2*WaterLily.pressure_force(sim.flow.p,sim.flow.f,sim.body,t)/(sim.L)
                
                #Append parameters to arrays in dict  
                CSV_write(wr_CSV, sim, forces)

                #Evolve flow
                biot_mom_step!(sim.flow,sim.pois,ω)

                #Evolve time
                t += sim.flow.Δt[end]
            end

            #Print progress
            println("tU/L=",round(tᵢ,digits=2),", Δt=",round(sim.flow.Δt[end],digits=3), ", -",round(t*sim.U/sim.L, digits=3))
        end

        #Close writer
        CSV_close(wr_CSV)
    end


#Set parameters 

    #Set Re 
    Re      =   80 #-

    #Set L (diameter)
    L       =   64 #-

    #Set domain 
    domain  =   [10,5]

    #Set nondimensional acceleration 
    acceleration_ND     =   5

#Make writers and set folders 

    #Set case name 
    case_name   =   "Test_am_map64-10x5"

    #Make CSV writer 
    CSV_writer      =   get_CSVWriter("forces_moving_body.csv", attributes_dict)

#Construct sim 
    #Construct simulation 
    sim     =   Circle_acc_to_const(L, Re, domain, acceleration_ND)

    #Get ω for Biot-Savart
    ω       =   MLArray(sim.flow.σ)

#Run simulation 

    t_star_max  =   0.5

    #Run
    run(sim, case_name, t_star_max, CSV_writer, ω)
``` 

Moving domain code: 

```julia
# Importing
    using WriteVTK, BiotSavartBCs, WaterLily, StaticArrays, CSV, DataFrames
    include("CSV_writer.jl")

#Simulation settings 

    #Limit time step by overwritting default function
    WaterLily.CFL(a::Flow) = WaterLily.CFL(a; Δt_max=0.2)

# CSV writer settings 

    #Set attributes 
    t_attrib(a::Simulation, forces) = sum(a.flow.Δt[1:end-1])*a.U/a.L;
    d_attrib(a::Simulation, forces) = forces[1];

    #Make attributes dict 
    attributes_dict         =   Dict("Time [-]" => t_attrib,
                                    "Drag [-]" => d_attrib) 

#Circle SDF 
    function TwoD_circle_sdf(x, radius, center)
        return √sum(abs2, x .- center) - radius
    end
    
#Motion function 
    function U_linear_to_constant(t, U, L, acceleration_ND)

        #Get t_i 
        t_i                 =   t*U/L 

        #Get t_acc
        t_acc               =   U/acceleration_ND

        #If accelerating, define motion for accelerating part 
        if t_i<t_acc
            updated_vel     =   acceleration_ND*t_i  
        
        else
            updated_vel     =   U

        end
    end

#Function to simulate circle with acceleration (2D)
    function Circle_acc_to_const(L,Re,domain,acceleration_ND;U=1,ϵ=0.5, f=Array)
        
        #Set radius and center 
        diameter, center  =   L, SA[domain[1]*L/2, domain[2]*L/2]

        #Set sdf 
        sdf     =   (x,t) -> TwoD_circle_sdf(x,diameter/2, center)

        #Get U of domain (horizontal velocity)
        U_domain    =   t -> U_linear_to_constant(t, U, L, acceleration_ND)

        #Get velocity vector of domain
        Ut(i,t::T) where T = i==1 ? convert(T,-U_domain(t)) : zero(T)

        #Write domain tuple
        domain_tuple    =   tuple(domain*L...)

        #Define simulation and return it
        Simulation(domain_tuple,Ut,L;U,ν=U*L/Re,body=AutoBody(sdf),ϵ, mem=f)
    end

    #Run 
    function run(sim, case_name, t_max_star, wr_CSV, ω)

        #Set t0 to be zero
        t₀ = 0.0 

        #Do actual simulation and store fields and forces
        @time for tᵢ in range(t₀,t₀+t_max_star;step=0.05)

            #Get current time (sum of delta t until now)
            t = sum(sim.flow.Δt[1:end-1])

            #While time is lower than normalised ti, keep running
            while t < tᵢ*sim.L/sim.U

                #Measure 
                measure!(sim,t)
            
                #Calculate forces 
                forces = 2*WaterLily.pressure_force(sim.flow.p,sim.flow.f,sim.body,t)/(sim.L)
                
                #Append parameters to arrays in dict  
                CSV_write(wr_CSV, sim, forces)

                #Evolve flow
                biot_mom_step!(sim.flow,sim.pois,ω)

                #Evolve time
                t += sim.flow.Δt[end]
            end

            #Print progress
            println("tU/L=",round(tᵢ,digits=2),", Δt=",round(sim.flow.Δt[end],digits=3), ", -",round(t*sim.U/sim.L, digits=3))
        end

        #Close writer
        CSV_close(wr_CSV)
    end


#Set parameters 

    #Set Re 
    Re      =   80 #-

    #Set L (diameter)
    L       =   64 #-

    #Set domain 
    domain  =   [10,5]

    #Set nondimensional acceleration 
    acceleration_ND     =   5

#Make writers and set folders 

    #Set case name 
    case_name   =   "Test_am64-10x5"

    #Make CSV writer 
    CSV_writer      =   get_CSVWriter("forces_moving_domain.csv", attributes_dict)

#Construct sim 
    #Construct simulation 
    sim     =   Circle_acc_to_const(L, Re, domain, acceleration_ND)

    #Get ω for Biot-Savart
    ω       =   MLArray(sim.flow.σ)

#Run simulation 

    t_star_max  =   0.5
    
    #Run
    run(sim, case_name, t_star_max, CSV_writer, ω)
``` 

CSV writer code: 

```julia
#Code that defines CSV writer structure 

using CSV
using WaterLily 

#CSV writer structure 
struct CSVWriter
    fname         :: String
    directory     :: String
    attributes    :: Dict{String,Function}
    output        :: Dict{String,Array}
end 

#Define function to construct correct CSV Writer 
function get_CSVWriter(directory, attributes,fname="WaterLily")

    #Make empty output dict 
    output  =   Dict()

    #For all keys in attributes, set same keys in output dict and fill with empty arrays
    for key in collect(keys(attributes)) 
        output[key]   =   []    
    end

    CSVWriter(fname,directory,attributes,output)
end

#Define write csv function
function CSV_write(w::CSVWriter, a::Simulation, forces)
    #For all attributes, calculate and store in output 
    for (key,func) in w.attributes
        #Compute and store to output 
        push!(w.output[key], func(a,forces))
    end
end

#Define function to close csv (and save it)

function CSV_close(w::CSVWriter)
    CSV.write(w.directory, DataFrame(w.output), delim = ';')
end
```

**Comment by marinlauber** [comment]
Hey Dirk, 

Thanks for picking this up. Maybe next time try to come up with a true MWE, without fileIO and this kind of stuff. It took me a while to make sure I was doing the same as you. Here is my MWE script

```
using WaterLily,StaticArrays
function make_sim_acc(; N=128, R=32, a=0.5, U=1, Re=1e3, mem=Array)
    circle(x,t) = √sum(abs2,x.-2N)-R # move the center
    Ut(i,t::T) where T = i==1 ? convert(T,ifelse(t≤U*R/a,a*t/R,U)) : zero(T) # velocity BC
    Simulation((4N,4N), Ut, R; U,ν=U*R/Re, body=AutoBody(circle), mem)
end
function make_sim(; N=128, R=32, a=0.5, U=1, Re=1e3, mem=Array)
    circle(x,t) = √sum(abs2,x.-2N)-R # move the center
    s(t) = ifelse(t≤U/a,0.5a*t^2,U*(t-0.5U/a)) # displacement
    move(x,t) = x + SA[R*s(t/R)-2R,0]
    Simulation((4N,4N), (0,0), R; U,ν=U*R/Re, body=AutoBody(circle,move), mem)
end
include("src/TwoD_plots.jl")

N = 2^7; R = N/4
acc = false
sim = acc ? make_sim_acc(mem=Array;N,R,Re=250) : make_sim(mem=Array;N,R,Re=250)
domain = inside(sim.flow.p)

forces = []
@gif for t in range(0,5;step=0.05)
    while sim_time(sim)<t
        measure!(sim,sum(@views(sim.flow.Δt))) # this is the same time as the force computation
        mom_step!(sim.flow,sim.pois)
        f = 2WaterLily.pressure_force(sim)
        push!(forces,[sim_time(sim),f[1]])
    end
    flood(sim.flow.p[domain],clims=(-1,1)); body_plot!(sim)
    @show t
end
```

if you un those you will realise the pressure field are different in the acceleration phase. This will directly translate into different forces and thus added-mass. I am not quite sure what the issue is, I suspect the pressure solver tolerances.

![circle_acc_body](https://github.com/user-attachments/assets/933ce4ea-8b86-463b-9d62-b33e02e2faf2)
![circle_acc_frame](https://github.com/user-attachments/assets/bf047966-6db0-433f-b578-2f54823dc6e3)

**Comment by b-fg** [comment]
Thanks @marinlauber for the detailed reply. @ddeboerfluid, does this solve your issue?

**Comment by ddeboerfluid** [comment]
Hi @b-fg, I talked with @marinlauber about it and as I am interested mostly in the post-acceleration phase, it will have no influence on my results (the flow fields after the acceleration are identical). However, I think the issue should still be open as it is still present: the drag force during acceleration is overestimated (seems to be an integer factor) when accelerating the flow.

**Comment by weymouth** [comment]
I think you're right. I've just posted a PR #178 which fixes this for 2D and 3D spheres and disks. We've also just merged some updates to the pressure solver #135. Can you confirm the PR fixes the issue? Does it cause any other issues?

**Comment by ddeboerfluid** [comment]
Thank you! That must be it. I will try updating my WaterLily version and see if that indeed solves the issue. For now I will close this, if I run into the same problem, I will reopen an issue again.

**Comment by ddeboerfluid** [comment]
I just started from scratch with the installation of WaterLily and I still get the same difference in added mass force when using map vs. when using moving boundary. So I reopen the issue.

**Comment by marinlauber** [comment]
@ddeboerfluid when you say that started from scratch, what do you mean? Did you install WL from the package manager or clone this repo and use these source files?

**Comment by ddeboerfluid** [comment]
Sorry for not being clear. I downloaded WaterLily as a zip file from this github, then unpacked it and in Julia package manager I did dev *path_to_WaterLily* and instantiate.

**Comment by marinlauber** [comment]
Using my [script](https://github.com/WaterLily-jl/WaterLily.jl/issues/160#issuecomment-2312649144) and the master branch I get very closely matched forces. There is just a singular pressure point when the acceleration stops, but the force is clean.

![issue_160_move](https://github.com/user-attachments/assets/dd246400-0221-4f2f-ad07-c0c6844db752)
![issue_160_acc](https://github.com/user-attachments/assets/d4de38fb-44e0-449b-bd95-d4a122299a49)
![issue_160_forces](https://github.com/user-attachments/assets/bd9957eb-20a9-453b-8c47-cc39a30d0020)

You can make sure you are using the correct `WaterLily` by doing `pathof(WaterLily)` in the RPEL, for me it return something like `"/home/marin/Workspace/WaterLily.jl/src/WaterLily.jl"`.

**Comment by ddeboerfluid** [comment]
I have the exact same when I run your script (I didn't plot the forces, but the fields show exactly that, including that short singular pressure). I also checked pathof(WaterLily) and it is the path that I installed an hour ago, from this github page.

Maybe the update works well for a circle, but not for a plate? Is there a quick way for you to exchange this MWE to a plate? 

Because in my plate examples, I get the pressure field still similar to what you showed for the circle before, surprisingly.

**Comment by marinlauber** [comment]
You just have to substitute your sdf into this setup...

```julia
using WaterLily,StaticArrays
using Plots
function make_sim_acc(; N=128, R=32, a=0.5, U=1, Re=1e3, mem=Array)
    circle(x,t) = √sum(abs2,x.-2N)-R # move the center
    plate(x,t) = (y=x.-2N; √sum(abs2,y.-SA[0,clamp(y[2],-R,R)])-2)
    Ut(i,t::T) where T = i==1 ? convert(T,ifelse(t≤U*R/a,a*t/R,U)) : zero(T) # velocity BC
    Simulation((4N,4N), Ut, R; U,ν=U*R/Re, body=AutoBody(plate), mem)
end
function make_sim(; N=128, R=32, a=0.5, U=1, Re=1e3, mem=Array)
    circle(x,t) = √sum(abs2,x.-2N)-R # move the center
    plate(x,t) = (y=x.-2N; √sum(abs2,y.-SA[0,clamp(y[2],-R,R)])-2)
    s(t) = ifelse(t≤U/a,0.5a*t^2,U*(t-0.5U/a)) # displacement
    move(x,t) = x + SA[R*s(t/R)-2R,0]
    Simulation((4N,4N), (0,0), R; U,ν=U*R/Re, body=AutoBody(plate,move), mem)
end

N = 2^7; R = N/4
acc = false
sim = acc ? make_sim_acc(mem=Array;N,R,Re=250) : make_sim(mem=Array;N,R,Re=250)
domain = inside(sim.flow.p)

forces = []
@gif for t in range(0,5;step=0.05)
    while sim_time(sim)<t
        sim_step!(sim;remeasure=true)
        f = 2WaterLily.pressure_force(sim)
        push!(forces,[sim_time(sim),f[1]])
    end
    flood(sim.flow.p[domain],clims=(-1,1)); body_plot!(sim)
    @show t
end
```

I can get the acceleration one to run, the moving one blows for some reason. I will keep looking.

![issue_160_acc_plate](https://github.com/user-attachments/assets/0fa8ca33-d1ba-4b25-89ab-4d6086f528a7)

**Comment by ddeboerfluid** [comment]
the MWE crashes for me as well for the case when using the map, not sure why.

Here is my results with the same WaterLily version, of my code (plate doing the same). 

![image](https://github.com/user-attachments/assets/65483209-616b-4fcd-9bf5-e71b4ebe96b4)

**Comment by weymouth** [comment]
I just tested a 2D and 3D plate for both of these and they matched great.

```julia
using WaterLily,StaticArrays
make_accel_plate(radius=8,H=8,thk=2) = Simulation(radius.*(2H,2H),
  (i,t)-> i==1 ? t : zero(t), radius; U=1,
  body=AutoBody((x,t)->(√(x[1]^2+(x[2]-min(x[2],radius-thk))^2)-thk),
                (x,t)-> abs.(x .- H*radius)))
sim = make_accel_plate(32,16); sim_step!(sim)
WaterLily.pressure_force(sim)/(π*sim.L^2) # [-1.066,0]
```
```julia
make_move_plate(radius=8,H=8,thk=2) = Simulation(radius.*(2H,2H), (0,0), radius; U=1,
  body=AutoBody((x,t)->(√(x[1]^2+(abs(x[2])-min(abs(x[2]),radius-thk))^2)-thk),
                (x,t)-> x .- H*radius - SA[t^2/2,0]))
sim = make_move_plate(32,16); sim_step!(sim)
WaterLily.pressure_force(sim)/(π*sim.L^2) # [1.066,0]
```

**Comment by ddeboerfluid** [comment]
@weymouth Thank you for the quick reply again.

They indeed match great for me. However, this is only the first sim step. I tried simulating for some time (using the code provided by @marinlauber before, with the sims you provided), and the one with the moving plate goes to NaN for me.

When trying the exact same code with my own SDF, it runs. But then again, I get a discrepancy in drag for the two cases (top=moving body, bottom=moving domain). 

![image](https://github.com/user-attachments/assets/8e49a430-f5fa-466c-8fc5-6fe0bad0d86d)

The SDF I use is shown below. L is the length of the plate. Body scales contains the length and thickness of the plate nondimensionalised by its length (eg. SA[1, 0.1] for a plate with thickness 1/10th its length). Centre is the location of the centre of the plate in the domain. In case of a domain of [4L, 4L] that would be [2L, 2L] (such that the plate is in the centre of the domain).

```
function SDF_plate_2D(x, L, body_scales, centre)
            
    #Get thickness from body scales 
    plate_thickness_ND  =   body_scales[2]/body_scales[1]
    thickness 		    =   plate_thickness_ND*L/2

    #Define distances to plate
    y = x .- SA[centre[1],clamp(x[2],-L/2 + centre[2] + thickness,L/2 + centre[2] - thickness)]
    return √sum(abs2,y)- thickness
end
```

**Comment by ddeboerfluid** [comment]
Also, I couldn't get my head around the SDF in the MWE, and the code in general (and plotting the right things).

When I run my own code, two cases being exactly the same, the only difference being the plate moving or the BC moving, I get the following pressure fields (hence, the difference in pressure during acceleration):


https://github.com/user-attachments/assets/4d3222b0-80e0-4782-8bdb-30f13aa83472


https://github.com/user-attachments/assets/2ed8f2a3-c677-41df-bd35-a2b77c55e03f

**Comment by weymouth** [comment]
Let's be wary of "issue creep"
The title of the issue is related to added mass force. That's exactly what the first time-step gives you, so those are now perfectly matching. So this issue was solved with #178.

It should of course also be true that the forces match (fairly well) later in the simulation. A second issue popped up - that my simple little example is messing up the `pcg!` smoother (again). I've just made PR #183, which has a patch for this. My same example above now gives me this plot for the first convective cycle:
```julia
WaterLily.CFL(a::Flow) = WaterLily.CFL(a;Δt_max=1) # good idea when accelerating from rest
time = 0.01:0.05:1.01

sim = make_accel_plate(16,16); 
drag_ref = map(time) do t
    sim_step!(sim,t)
    -WaterLily.pressure_force(sim)[1]/(π*sim.L^2)
end

sim = make_move_plate(16,16);
drag_move = map(time) do t
    sim_step!(sim,t)
    WaterLily.pressure_force(sim)[1]/(π*sim.L^2)
end

plot(time, drag_move, label="moving plate", xlabel="tU/R", ylabel="C_D")
plot!(time, drag_ref, label="accelerating background", ylims=(0,12))
```
![compare](https://github.com/user-attachments/assets/fb8598cb-1792-48ae-ab74-af85fb998c3e)

Which looks great, so the solver is doing its job properly in either reference. We don't expect the two references frames to match _perfectly_ because we're solving on a finite grid with a finite domain and the bodies are in different places with different body and domain BCs. I'm going to close this issue and merge that patch ASAP.

If you are still having problems you should come up with a specific MWE and try to drill down to the core issue as deep as you can by yourself before posting. If there are big discrepancies later in the simulation then it's either one of those unavoidable things mentioned above, or maybe a bug that we can fix. Again - you'll have to do a little digging to sort that out.

**Comment by ddeboerfluid** [comment]
@weymouth Thanks for the clear reply, and indeed these are two difference issues. I just pulled the current version from Github and still get the same:

1. Your example with the moving plate goes to NaN
2. My personal example (which also uses the Biot-Savart BC, don't think this should influence it?) keeps getting the pressure field wrong for the moving domain case.

My knowledge is limited, and I didn't really understand what the exact thing is that you mentioned to be in a new merge. What is the bug that is fixed? That it does not go to NaN aymore? or that the pressure fields are better later in the motion? And is this still to merge, or did this already happen?

Thanks again

**Comment by weymouth** [comment]
This PR #183 stops the NaN. I haven't run you case, so I'm not sure what's going on with that.

**Comment by ddeboerfluid** [comment]
Thank you! Did this PR already merge?

**Comment by weymouth** [comment]
I just did it. You can also try out PRs (or any other version of the code you want) using
`] add WaterLily#git_hash`

**Comment by ddeboerfluid** [comment]
Thank you! Now I indeed get the same result running your code.

However, changing some minor things gives me weird/wrong results. It might also be me misinterpreting some WaterLily functions.

1. I noticed you used ```WaterLily.pressure_force(sim)[1]``` in your code. Before, I always used ```WaterLily.pressure_force(sim.flow.p,sim.flow.f,sim.body,sim_time(sim))[1]```. However, in the moving plate case, these give very different results except at the start (using your code from before with the code below):

```julia
sim = make_move_plate();

t2, d3, d4  = [], [], [] 

while sim_time(sim)<1
    measure!(sim, sim_time(sim))
    sim_step!(sim) #sim_step!(sim)
    push!(t2, sim_time(sim))
    push!(d3, WaterLily.pressure_force(sim.flow.p,sim.flow.f,sim.body,sim_time(sim))[1]/(π*sim.L^2))
    push!(d4, WaterLily.pressure_force(sim)[1]/(π*sim.L^2))
end

plot(t2, d3, label="moving plate (sim.p etc)", xlabel="tU/R", ylabel="C_D")
plot!(t2, d4, label="moving plate (sim)")

``` 

2. I wanted to check if my discrepancy in forces could be the consequence of using BiotSavartBCs, so I wanted to check the difference between ```julia mom_step!(sim.flow, sim.pois)``` and ```julia biot_mom_step!(sim.flow, sim.pois, ω)```. However, I noticed in your code you use ```julia sim_step!(sim)``` instead. I was confused as I did not know about a difference between the two. In the moving domain case, it does not give different forces, but in the moving plate case it does (using your code from before with the code below):

```julia
sim = make_move_plate();

t2, t3, d3, d4 = [], [], [], []

while sim_time(sim)<1
  measure!(sim, sim_time(sim))
  mom_step!(sim.flow, sim.pois) #sim_step!(sim)
  push!(t2, sim_time(sim))
  push!(d3, WaterLily.pressure_force(sim)[1]/(π*sim.L^2))
end

sim = make_move_plate();

while sim_time(sim)<1
  measure!(sim, sim_time(sim))
  sim_step!(sim) #sim_step!(sim)
  push!(t3, sim_time(sim))
  push!(d4, WaterLily.pressure_force(sim)[1]/(π*sim.L^2))
end

plot(t2, d3, label="moving plate (mom step)", xlabel="tU/R", ylabel="C_D")
plot!(t3, d4, label="moving plate (sim step)")
```

**Comment by marinlauber** [comment]
@ddeboerfluid 

It is best not to specify the time yourself for all these functions. Internally, the solver handles the time correctly, the functionality is still there for some specific cases requiring custom function calls.

`sim_step!(sim;remeasure=true)` should be your default call to update the simulation (body and flow) and replace `measure!(...); mom_step!(...)`. Similarly, you should use `WaterLily.pressure_force(sim)` for the force. This ensures that the time is handled correctly.

Ultimately, the issue you have here is that when you do `pressure_force(sim)`, the force is computed at `t=time(sim)` and not `t=sim_time(sim)`, which is what you specify, so for identical kinematics, one is correct and not the other one.

**Comment by marinlauber** [comment]
@ddeboerfluid 

The `BiotSavartBCs.jl` will get a complete makeover in the coming weeks; maybe wait for this and check again. When it is done, you will be able to call `sim_step!()` for both normal simulations and simulations using BiotSavart.

**Comment by ddeboerfluid** [comment]
Thanks @marinlauber @weymouth, I will wait for the BiotSavartBC update then.

**Comment by ddeboerfluid** [comment]
What about combining symmetry with BiotSavartBC.jl? Will there also be an update related to that?
